version: '3'
volumes:
  node_modules:
services:
  ludo_f2e:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
        - "127.0.0.1:3000:3000"
    # in future, we might use it
    # env_file:
    #     - ./.env.dev
    volumes:
        - ./:/var/www/app
        - node_modules:/var/www/app/node_modules