FROM node:11.13-alpine

ENV NODE_ENV development

RUN mkdir -p /var/www/app
WORKDIR /var/www/app

RUN apk add ncurses

COPY ./package.json ./package-lock.json /var/www/app/
RUN npm install

ENV HOST 0.0.0.0
EXPOSE 3000
CMD npm run dev