version: '3'
volumes:
  node_modules:
services:
  ludo_f2e:
    # image: ludo_frontend_base_server:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - reverse-proxy
      - back
    ports:
        - "3001:3000"
    environment:
      - BASE_URL=https://www.ludonow.com
      - API_URL=https://api.ludonow.com
      - RUNTIME_ENV=production
      - VIRTUAL_PORT=3001
      - VIRTUAL_HOST=yoga.ludonow.com
      - LETSENCRYPT_HOST=yoga.ludonow.com
      - LETSENCRYPT_EMAIL=sean@ludonow.com
    restart: always
    # volumes:
        # - ./:/var/www/app
        # - node_modules:/var/www/app/node_modules
    # command: npm run dev
    command: npm start

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge