module.exports = [
    {
        id: '1',
        title: '骨盆矯正',
        chapter_flag: '/mamiyoga/course/unit01.svg',
        tags: ['rectify'],
        ai_teacher: false,
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
        course_introduction:'骨盆位於身體上半部跟下半部的中間點，它不單單只是分隔開身體，也扮演著支撐身體的重要角色哦。<br>為什麼說它重要呢？讓我們一起觀看麻美老師的說明與教學',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '讓身體記憶骨盆的正位',
                pose_video:'',
                pose_description:['雙腳張開，比腰再寬一點','兩手壓住前後骨盆','讓骨盆前後移動','感受背部打直，不要駝背','記住骨盆移動的感覺','重複動作十次'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '躺著也可以做的骨盆矯正姿勢',
                pose_video:'',
                pose_description:['側躺在瑜珈墊上','手臂支撐頭部','兩隻腳膝蓋彎曲','上面的腳彎曲90度，舉起到身前','下方的腳伸直','吸氣，讓彎曲的膝蓋向天空張開','吐氣，慢慢將膝蓋放回原點','重複十次之後，換另一邊'],
                pose_ai:true,
            },
            {
                pose_id: 'third',
                pose_brief: '回到沒有歪斜的骨盆',
                pose_video:'',
                pose_description:['雙腳張開，比腰再寬一點','兩手壓住前後骨盆','讓骨盆前後移動','感受背部打直，不要駝背','記住骨盆移動的感覺','重複動作十次',''],
                pose_ai:true,
            },
        ],
    },
    {
        id: '2',
        title: '改善疼痛症狀的伸展',
        chapter_flag: '/mamiyoga/course/unit02.svg',
        tags: ['rectify'],
        ai_teacher: true,
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '3',
        title: '',
        chapter_flag: '/mamiyoga/course/unit03.svg',
        tags: ['rectify'],
        ai_teacher: true,
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '讓身體記憶骨盆的正位',
                pose_video:'',
                pose_description:['雙腳張開，比腰再寬一點','兩手壓住前後骨盆','讓骨盆前後移動','感受背部打直，不要駝背','記住骨盆移動的感覺','重複動作十次',''],
            },
            {
                pose_id: 'second',
                pose_brief: '躺著也可以做的骨盆矯正姿勢',
                pose_video:'',
                pose_description:['雙腳張開，比腰再寬一點','兩手壓住前後骨盆','讓骨盆前後移動','感受背部打直，不要駝背','記住骨盆移動的感覺','重複動作十次',''],
            },
        ],
    },
    {
        id: '4',
        title: '伸展鼠蹊部的姿勢',
        chapter_flag: '/mamiyoga/course/unit04.svg',
        tags: ['alleviate'],
        ai_teacher: true,
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '5',
        title: '睡醒好狀態的姿勢',
        chapter_flag: '/mamiyoga/course/unit05.svg',
        tags: ['alleviate'],
        ai_teacher: true,
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '6',
        title: '舒緩疲勞和倦怠感',
        chapter_flag: '/mamiyoga/course/unit06.svg',
        tags: ['beauty'],
        ai_teacher: true,
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '7',
        title: '鬆弛的肚子變得緊實',
        chapter_flag: '/mamiyoga/course/unit07.svg',
        tags: ['beauty'],
        ai_teacher: true,
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '8',
        title: '',
        chapter_flag: '/mamiyoga/course/unit08.svg',
        tags: ['beauty'],
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '9',
        title: '',
        chapter_flag: '/mamiyoga/course/unit09.svg',
        tags: ['beauty'],
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '10',
        title: '同時照顧上半身跟下半身',
        chapter_flag: '/mamiyoga/course/unit10.svg',
        tags: ['blend'],
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '11',
        title: '呼吸法',
        chapter_flag: '/mamiyoga/course/unit11.svg',
        tags: ['blend'],
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '12',
        title: '',
        chapter_flag: '/mamiyoga/course/unit12.svg',
        tags: ['blend'],
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '13',
        title: '',
        chapter_flag: '/mamiyoga/course/unit13.svg',
        tags: ['blend'],
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
    {
        id: '14',
        title: '',
        chapter_flag: '/mamiyoga/course/unit14.svg',
        tags: ['blend'],
        preview_img: '/mamiyoga/background-menu-old.png',
        video_url:'',
    },
]
    