module.exports = [
    {
        id: '1',
        title: '骨盆矯正瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit01.svg',
        tags: ['rectify'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-1.png',
        video_url:'https://player.vimeo.com/video/349924443',
        video_url_jp:'https://player.vimeo.com/video/350479253',
        course_introduction:'產時造成的韌帶變鬆，一般要回復，通常最快得要需要三到四個月，最慢也得要耗上六個月。而這時候，骨盆是處在較鬆弛狀態，也同時是做骨盆矯正的絕佳時候，所以，當媽媽們子宮收縮情形開始比較緩和的時候，大概是產後一個月，就可以慢慢開始矯正骨盆。<br>除此之外，矯正骨盆的歪斜還有另外一項很棒的效果哦！那就是可以讓腰部周圍較難附著脂肪，讓新陳代謝向上，這些都有非常顯著的減肥效果喔！所以，這麼棒的機會，我們一起好好努力，來把骨盆矯正到最佳狀況吧！',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '讓身體記憶骨盆的正位',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L1_action01.mp4',
                pose_description:['雙腳張開，比腰再寬一點','兩手壓住前後骨盆','讓骨盆前後移動','感受背部打直，不要駝背','記住骨盆移動的感覺','重複動作十次'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '躺著也可以做的骨盆矯正姿勢',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L1_action02.mp4',
                pose_description:['側躺在瑜珈墊上','手臂支撐頭部','兩隻腳膝蓋彎曲','上面的腳彎曲90度，舉起到身前','下方的腳伸直','吸氣，讓彎曲的膝蓋向天空張開','吐氣，慢慢將膝蓋放回原點','重複十次之後，換另一邊'],
                pose_ai:false,
            },
            {
                pose_id: 'third',
                pose_brief: '回到沒有歪斜的骨盆',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L1_action03.mp4',
                pose_description:['首先模仿趴睡的姿勢','兩隻手肘將上半身撐起','調整手肘讓雙臂與肩同寬','抱持手肘位置，右膝蓋往腰部下方靠近','右膝撐地，用大腿的力量將身體撐起','右腿：腰部與大腿是九十度、大腿與小腿也是九十度','左腿：大腿小腿貼在地板上，腳掌朝後與小腿90度','臉部朝前，重複三到五次呼吸','另一邊也做相同的動作','屁股碰到後腳跟，手伸直手掌貼地伸直背部後緩緩坐起'],
                pose_ai:false,
            },
        ],
    },
    {
        id: '2',
        title: '可以邊躺邊做的疲勞恢復瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit02.svg',
        tags: ['rectify'],
        ai_teacher: true,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-2.png',
        video_url:'https://player.vimeo.com/video/350050968',
        video_url_jp:'https://player.vimeo.com/video/350481218',
        course_introduction:'血液若是流動不良會衍生許多疼痛或不適感：例如肩頸酸痛，腰痛，浮腫，手腳冰冷的狀況。而且，媽媽們產後不只要哺乳，也會需要抱小孩、背小孩，這些動作往往會使得母親得持續做出前傾的姿勢，這姿勢容易讓肌肉僵硬。<br>預防重於治療，若我們能在身體在發出疼痛的警訊前，搶先照顧好，就能夠避免這些身體症狀。',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '減緩腰部疼痛',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L2_action01.mp4',
                pose_description:['正躺，眼睛看向天花板','左膝抬高，兩手抱住膝蓋','雙掌托住膝蓋，讓雙手臂伸直','將右腳抬起，用腰部的力量將整條腿做上下擺動三到五次','腰部有一點拱起來是可以的','（如果很吃力的同學可以把毛巾捲起來放在腰下）','右腳做完，換左邊做三到五次'],
                pose_ai:true,
            },
            {
                pose_id: 'second',
                pose_brief: '雙腳消解浮腫的姿勢',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L2_action02.mp4',
                pose_description:['正躺，眼睛看向天花板','大腿小腿彎曲像一座小山，腳掌貼地','抬起雙腳，在空中踩腳踏車','記得要讓上身維持穩定，意識到核心肌肉','重複十次，慢慢將雙腳放下'],
                pose_ai:false,
            },
            {
                pose_id: 'third',
                pose_brief: '消除疲勞的睡眠姿勢',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L2_action03.mp4',
                pose_description:['首先進入趴睡的姿勢','趴下的同時，依照脖子的習慣面向左或右邊','接著把雙手慢慢放在身體兩側','呼吸，臉頰貼著瑜珈墊或地板','呼吸，讓腿自然伸直、與腰同寬','呼吸，掌心朝上、手肘彎曲90度','一次進行30秒到一分鐘','結束後慢慢起身'],
                pose_ai:false,
            },
        ],
    },
    {
        id: '3',
        title: '讓呼吸變深的瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit03.svg',
        tags: ['rectify'],
        ai_teacher: true,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-3.png',
        video_url:'https://player.vimeo.com/video/350540141',
        video_url_jp:'https://player.vimeo.com/video/350482701',
        course_introduction:'我們常常在一整天的辛苦勞動後，身心因此變得很緊繃。在這樣還沒有辦法把緊崩狀態好好切換回來的情況下，即便上床睡覺，也是沒有辦法獲得有效率的休息。沒有辦法好好睡著，甚至半夜的時候會不斷醒來，這樣下去的話，怎麼睡都沒有辦法讓疲勞感消失。若是沒有辦法獲得良好的睡眠品質，疲勞感隔天也會繼續跟著你。<br>所以，讓身體攝取大量新鮮空氣，讓身心好好放鬆，一起消除整天的疲勞吧！',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '用空氣啟動身體',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L3_action01.mp4',
                pose_description:['輕鬆盤腿坐在墊子上','吸氣，把右手向上抬起','吐氣，身體往左傾、意識到右側身體的肌肉伸展','吸氣，換左手向上抬起','吐氣，身體往右傾、意識到左側身體的肌肉伸展','重複三到五次'],
                pose_ai:true,
            },
            {
                pose_id: 'second',
                pose_brief: '深呼吸、深呼吸',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L3_action02.mp4',
                pose_description:['捲起棉被或使用抱枕','放在屁股後面，可以碰到腰部的位置','調整到舒適的高度，緩緩躺下來','將腿打開放置在墊子的兩側','手掌面向天花板，放在身體兩側','深呼吸、感受胸部的擴張','起身時感受身體習慣的方向，從該方向慢慢起身'],
                pose_ai:false,
            },
        ],
    
    },
    {
        id: '4',
        title: '讓淋巴液流暢的瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit04.svg',
        tags: ['alleviate'],
        ai_teacher: true,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-4.png',
        video_url:'https://player.vimeo.com/video/350494809',
        video_url_jp:'https://player.vimeo.com/video/350491544',
        course_introduction:'一旦淋巴液堵塞，就沒有辦法將體內不好的物質以及多餘的水分排出。這會連帶免疫力的功能也一起下降，非常嚴重。淋巴堵塞，會造成讓人頭痛、肩膀僵硬、疲勞久久難消，容易患上感冒等等……各種讓身體不舒服的症狀。<br>所以讓淋巴液好好流通是很重要的！這不只能改善身體不好的狀況，還能進一步讓新陳代謝變得夠好，獲得清爽的身體曲線哦！',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '打通壓力沉積的地方',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L4_action01.mp4',
                pose_description:['坐在墊子上，將腳掌對腳掌','兩手各握住兩邊腳趾','將左腳伸直','右腳彎曲且靠攏恥骨','讓伸展的左腳跟往後扣、腳趾朝自己方向','一邊吸氣、一邊擴胸','一邊吐氣、一邊前傾','一邊吸入空氣、放鬆','最後慢慢將上半身撐起來','換邊，以反方向換腿做一樣的動作'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '讓能量在身體流轉',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L4_action02.mp4',
                pose_description:['張開雙腳，直到你覺得舒服的範圍','雙臂放在身體的兩側','吸氣，讓右手大大的往上伸展','吐氣，讓整個上半身往左傾倒','左手握住左腳的後腳跟，伸展到可以伸展的程度就好','吸氣，邊讓上半身回來','換邊，兩邊動作各重複10次'],
                pose_ai:true,
            },
        ],
    },
    {
        id: '5',
        title: '讓人煥然一新的瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit05.svg',
        tags: ['alleviate'],
        ai_teacher: true,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-5.png',
        video_url:'https://player.vimeo.com/video/350540867',
        video_url_jp:'https://player.vimeo.com/video/350476133',
        course_introduction:'媽媽們在生產後，因為常常為了照顧嬰兒，一直都沒有充足的睡眠時間。長期下來，就會疲勞堆積，睡眠不足造成的荷爾蒙失衡更會使得媽媽們情緒變得負面。所以，緩解已經僵硬的肌肉，讓體內的血液循環變好，就可以更有效緩解疲勞。不管是早上起床時，常容易感到很累，或者是覺得沒有幹勁時，做這些動作，都可以讓媽媽們重新獲得活力，心情也因此煥然一新，整天可以舒適地面對工作喔！<br>只要花10分鐘，就可以讓媽媽們在起床的時候可以感覺自己的精神回復到極好的狀態，所以請務必跟著我一起試試看吧。',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '新的一天！新的開始！',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L5_action01.mp4',
                pose_description:['雙腳與腰同寬站立','把手放在腰部兩側','吸氣時，伸展背部肌肉','吐氣時，讓身體折成兩半','輕輕彎曲膝蓋，身體往下，讓頭頂朝向地板','呼吸三次之後就可以慢慢地起來','記得，讓頭部要最後才起來哦！'],
                pose_ai:true,
            },
            {
                pose_id: 'second',
                pose_brief: '改善背部與肩部僵硬',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L5_action02.mp4',
                pose_description:['採取輕鬆的姿勢坐下','在胸前把手臂交叉','一邊吐氣讓背部稍微拱起','將雙手十指交扣','想像腹部跟手腕當中產生空間','吸氣讓身體舒展開','將雙手放到身體後方十指交扣','意識到兩邊的肩胛骨向脊椎靠近','把氣全部吐完後，下一次呼吸時擴胸','更進一步的人，可以把臉朝上試試看','回到原本位置時要慢慢地回去，再把手放開'],
                pose_ai:true,
            },
        ],
    },
    {
        id: '6',
        title: '從身體內部守護的產後瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit06.svg',
        tags: ['beauty'],
        ai_teacher: true,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-6.png',
        video_url:'https://player.vimeo.com/video/350541736',
        video_url_jp:'https://player.vimeo.com/video/350474009',
        course_introduction:'懷孕時因為抱著一個很大很大的肚子，運動量也會被迫減少很多。所以，往往生產後，肌肉量也會變得很低、基礎代謝率也會變差。<br>不過，我們可以在生產後利用日常時間做瑜珈，讓肌肉量一點一點上升，體力變得愈來愈好，讓我們一起為照顧小孩的辛苦生活做準備吧！',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '啟動核心肌群',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L6_action01.mp4',
                pose_description:['將四肢趴在地上','腳趾立在墊子上，屁股朝天花板抬高','肩膀對應到手腕的位置，膝蓋對應到腰下的位置','一邊吸氣一邊把屁股抬高到天花板','感受肩膀向外向後旋開，腳跟踩在地板上','不是用手臂的力量支撐身體，而是用背部的力量','覺得太困難的人可以讓後腳跟呈現浮起來的狀態、彎曲膝蓋也是可以的','保持住，並呼吸五次','慢慢的讓膝蓋碰到墊子上，回到四肢趴在地上的姿勢','一邊吸氣一邊讓背部變圓','把視線放在肚子，慢慢回到原本的姿勢'],
                pose_ai:true,
            },
            {
                pose_id: 'second',
                pose_brief: '加強骨頭密度',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L6_action02.mp4',
                pose_description:['腳輕輕開到與腰同寬','雙手放在兩側腰上','慢慢地把後腳跟往上抬','變成用腳趾站起來的狀態','一鼓作氣讓後腳跟放到地板','也可以一邊抓著椅子或桌子去做這個動作'],
                pose_ai:true,
            },
        ],
    },
    {
        id: '7',
        title: '解消產後肥胖的瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit07.svg',
        tags: ['beauty'],
        ai_teacher: true,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-7.png',
        video_url:'https://player.vimeo.com/video/350543195',
        video_url_jp:'https://player.vimeo.com/video/350471282',
        course_introduction:'媽媽們的骨盆和髖關節就會變廣變鬆弛，然後大腿骨的一部分，就會開始往外側突出去。這會造成產後鬆弛，骨盆周邊容易有脂肪附著。這樣一來，腰部和肚子周邊，還有臀部跟大腿，就很容易有脂肪附著。有些媽媽們產後的下半身肥胖就是這樣產生的。但是，如果媽媽們只是著急地想要緩解下半身的肥胖。卻沒有方向的激烈訓練，很容易就會弄壞身體了。<br>所以，讓我們一邊緩解骨盆周邊的肌肉，ㄧ點一點地刺激肌肉，讓他慢慢地變得緊實吧！',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '讓肚子變得更緊實',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L7_action01.mp4',
                pose_description:['曲膝坐下','兩手放在膝蓋後方','直直的挺立背部，以腹肌的力量把腳抬起來','維持將腳彎曲成90度的動作','放在膝蓋的手，邊開擴胸邊慢慢地往前伸','維持三到五次的呼吸','把手放回膝蓋後方的位置','一邊吐氣把腳放在地上調整呼吸'],
                pose_ai:true,
            },
            {
                pose_id: 'second',
                pose_brief: '回復產後的翹臀',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L7_action02.mp4',
                pose_description:['將四肢都趴在地上，調整呼吸','膝蓋呈90度，然後讓大腿跟地墊呈現平行的狀態','把腿往後抬起來','骨盆一旦變成跟墊子平行，就要注意腰部不要太開','要一邊注意一邊這些細節，一邊進行動作','一邊吸氣，一邊把膝蓋放到右邊','保持與腰同高，接著，放下來','我們就這樣連續重複三次','換邊','結束之後，就要把屁股放回後腳跟，把頭放下稍微休息'],
                pose_ai:false,
            },
            {
                pose_id: 'third',
                pose_brief: '收緊骨盆，告別大屁股',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L7_action03.mp4',
                pose_description:['把兩個膝蓋立起來，腳掌貼地，躺著看天花板','讓後腳跟移到屁股下緣','雙腳間距要與腰同寬','一邊吸氣，一邊從地墊抬高臀部跟腰部，讓腰整個抬起來','手臂交叉讓肩胛骨靠近','使大腿跟地墊平行','兩個膝蓋在後腳跟的正上方位置','在覺得舒服的時機點呼吸','吐氣的時候，慢慢地放鬆背部骨頭，回到原本的姿勢'],
                pose_ai:true,
            },
        ],
    },
    {
        id: '8',
        title: '製造身體曲線的瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit08.svg',
        tags: ['beauty'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-8.png',
        video_url:'https://player.vimeo.com/video/350545331',
        video_url_jp:'https://player.vimeo.com/video/350470076',
        course_introduction:'腹斜肌不是只單單能替媽媽們帶來美麗的曲線，還有一個重要的功能噢！就是能扮演著將內臟維持在正確位置的角色，就像束腹一樣。包覆在我們的肚子周邊。<br>如果持續鍛鍊腹斜肌，就像是有條漂亮的束腹，能維持腰部緊實的狀態。大家都很嚮往有著像模特兒那樣，讓人煞羨的腰部曲線，對吧？',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '雕塑腰部曲線',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L8_action01.mp4',
                pose_description:['四肢趴在地上','讓腳尖從地板浮起來','一邊吐氣一邊慢慢地把腰朝右方扭去','意識集中在腰部','慢慢地回到正面','重複三到五次','另外一邊也要做一樣的動作'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '雕塑容易遺忘的部位',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L8_action02.mp4',
                pose_description:['先跪坐（正坐）','讓腳開得比腰部的幅度還要大','把手放在膝蓋上吸氣','擴胸一邊吐氣','把右手放在身體後面，左手放在右邊膝蓋','慢慢地把身體往右開，扭轉的時候','在舒適的地方停下來就好，不需要太深','重複三到五次的自然呼吸，一邊吸氣慢慢回到正面','手放回兩邊膝蓋上，這整個動作要做三到五次','另外一邊也要做同樣的動作'],
                pose_ai:false,
            },

        ],
    },
    {
        id: '9',
        title: '產後的腹肌瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit09.svg',
        tags: ['beauty'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-9.png',
        video_url:'https://player.vimeo.com/video/350546192',
        video_url_jp:'https://player.vimeo.com/video/350467858',
        course_introduction:'我們要做的，都不是激烈的運動，而是用瑜珈慢慢地，溫柔地去鍛煉這些核心肌群。一旦鍛煉了核心肌群，鬆弛的肌肉也會跟著被鍛煉。這樣，肚子周邊就會跟著緊實起來。<br>另一方面，只要內臟被刺激，新陳代謝就會活化，所以對於改善水腫，腰痛，甚至讓腸胃功能提高，緩解便秘，也是非常非常有效的喔！',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '感受腹部收縮',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L9_action01.mp4',
                pose_description:['先讓膝蓋立著，坐起來','把手放到膝蓋後方','兩隻手掌交叉抓住手肘','一邊吸氣，一邊伸直背部肌肉','地上抬起兩腳','小腿肚跟地板平行之後','維持10-30秒','重複三到五次'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '消除令人困擾的下腹',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L9_action02.mp4',
                pose_description:['看著天花板躺下，彎曲兩個膝蓋','讓膝蓋往自己胸口的方向靠攏','兩手壓著骨盆，一邊吐氣，一邊把右腳往前伸','不要讓後腳跟與小腿肚碰到地板','一邊吸氣一邊把腳放回去','另外一邊也要重複這樣的動作','重複5-10次'],
                pose_ai:false,
            },
            {
                pose_id: 'third',
                pose_brief: '鍛鍊產後腹肌',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L9_action03.mp4',
                pose_description:['仰躺看著天花板，將腳掌貼地，把兩個膝蓋立起','把兩手伸直往前伸','一邊吸氣然後一邊吐氣，專注著下腹的部分','輕輕地將上半身往前抬','收起下巴，吸氣，吐氣，慢慢上來','重複10次'],
                pose_ai:false,
            },
        ],
    },
    {
        id: '10',
        title: '產後的下半身減肥瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit10.svg',
        tags: ['blend'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-10.png',
        video_url:'https://player.vimeo.com/video/350547825',
        video_url_jp:'https://player.vimeo.com/video/350465960',
        course_introduction:'大腿內側裡面的「內轉肌」在日常生活中，若沒有特別有意識鍛鍊使用，就不會用到的。那是一個容易低溫，容易囤積橘皮組織的地方。<br>只要內轉肌肉一旦衰退，腳閉合的時候力量就會變弱、容易變成O型腿。血液跟淋巴的循環也會變遲鈍，容易水腫。這樣下去的話，腳就會越來越粗！所以在那之前，我們得要好好照顧這個部位！',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '同時照顧上半身與下半身',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L10_action01.mp4',
                pose_description:['雙腳站得比肩膀再寬一點','將屁股往下坐，像是紮馬步一樣','稍微把腳尖往外挪一點，像是微微外八','把雙手放在腿上，吸氣時，伸直背肌','邊吐氣，邊壓下單邊肩膀把屁股放下','肩頸用力，讓雙腳掌跟瑜珈墊貼齊','配合自己的呼吸，保持放鬆舒適','反覆進行個五次'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '讓肚子與下腹同時瘦下來',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L10_action02.mp4',
                pose_description:['正躺看著天花板','讓兩個膝蓋往上抬起','手掌抓著墊子','吸口氣讓腳交叉','吐氣後往反方向交叉','有節奏感的重複各10次'],
                pose_ai:false,
            },
        ],
    },
    {
        id: '11',
        title: '療癒的呼吸法',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit11.svg',
        tags: ['blend'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-11.png',
        video_url:'https://player.vimeo.com/video/349015764',
        video_url_jp:'https://player.vimeo.com/video/348991213',
        course_introduction:'忙碌的每一天，如果呼吸變淺的話，就會影響到大腦跟自律神經。隨著壓力越來越大，你總是覺得好像有點焦躁不安，那就代表你的呼吸變淺了。而且，因為氧氣不足時，你的內臟的功能也會跟著變差。<br>不過，瑜珈的深沈呼吸裡，就會有能達到放鬆副交感神經的效果。這會促進讓精神變安定感，感受到幸福感的血清素分泌，讓你擁有平穩的心情。',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '瑜珈的基本呼吸',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L11_action01.mp4',
                pose_description:['輕鬆的姿勢坐下','輕輕的閉上眼皮','把意識集中在自己的呼吸','平靜下來後就可以開始換到腹式呼吸','從鼻子一邊吸氣一邊膨脹肚子','在從鼻子吐氣讓肚子凹進去','到平靜為止，重複數次'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '單邊鼻子呼吸法',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L11_action02.mp4',
                pose_description:['彎曲右手的食指跟中指用右手的拇指去壓右邊的鼻孔','從左邊的鼻孔呼吸，用右手的第四根手指跟小指去壓左邊的鼻孔','右手的拇指放開，從右邊的鼻孔吐氣','從右邊的鼻孔呼吸，用右邊的拇指去壓住右邊的鼻孔','右邊的第四根手指跟小指放開','從左邊的鼻孔吐氣','重複數次'],
                pose_ai:false,
            },
        ],
    },
    {
        id: '12',
        title: '讓睡眠品質變好的瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit12.svg',
        tags: ['blend'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-12.png',
        video_url:'https://player.vimeo.com/video/350438391',
        video_url_jp:'https://player.vimeo.com/video/350040395',
        course_introduction:'24小時制的照顧小孩會讓生活節奏變亂，讓體內的節奏，就是生理時鐘也會變亂走樣，便會產生睡不著的狀況。照顧小孩也因此沒有辦法很順利，家事也做不太起來。連自己都沒有發現累積了很多壓力，最後變成睡不著的狀況。<br>為了要回復疲勞，讓身心變平穩，休息是很重要的。這次要介紹兩種姿勢：睡覺前的十分鐘，不妨試試深呼吸放鬆呢？',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '用呼吸創造放鬆空間',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L12_action01.mp4',
                pose_description:['設置瑜珈磚和瑜珈枕後，把屁股後面墊上瑜珈磚','沒有瑜珈磚和瑜珈枕的人可以用棉被裹起來代替','將背部靠在上面，慢慢地面朝天空地躺下來，讓腳底碰到地板','把手放在肚子上，像是要溫暖他ㄧ般，或是把手掌面向上，放到身體兩側','慢慢地放輕鬆，把身體的力量抽掉','放鬆持續三到五個呼吸','回去的時候把腳閉合，把手放下','讓手肘壓著墊子，起身'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '讓全身的神經進入休息',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L12_action02.mp4',
                pose_description:['先仰躺看天花板，讓腳開與墊子同寬','手掌面向天花板，在腋下留一個拳頭的空間','慢慢地閉上眼睛把全身的力量都交給墊子','把頭左右搖一搖、滾一滾','從口中吐哈～這樣的把全身力量放鬆','進行5-10分鐘，不讓身體變冷的程度','身上也可以蓋上棉被保暖','腦中什麼都不用想的放鬆','持續著自然的呼吸','起身的時候，先從末端的手足收緊、放鬆（石頭、布、石頭、布），開著握著重複','讓整個身體起床','再把頭左右搖晃，讓兩個膝蓋立起來。','把身體往旁邊，慢慢地起身'],
                pose_ai:false,
            },
        ],
    },
    {
        id: '13',
        title: '消除壓力的瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit13.svg',
        tags: ['blend'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-13.png',
        video_url:'https://player.vimeo.com/video/350549096',
        video_url_jp:'https://player.vimeo.com/video/350465109',
        course_introduction:'讓我們來打開心胸，攝取正面能量，感受到向前走的感覺吧！打開心胸跟喉嚨就可以攝取新鮮空氣，自然心情也會變得清爽。<br>對於不習慣的新生活，照顧小孩，感受到疲勞，焦慮，喘不過氣來時，這時候做這些動作就可以感受到可以煥然一新。因為產後非常忙碌，感覺怎麼樣都追不上時間...所以，必須要更重視自己煥然一新的時間！那麼我們來馬上開始吧！',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '為自己的心情按摩',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L13_action01.mp4',
                pose_description:['首先先用舒服的姿勢坐下來','用兩手手指輕抓住頭頂，用指尖輕輕按摩頭頂','重複著自然的呼吸就可以了'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '沒關係，暫時放下心事吧！',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L13_action02.mp4',
                pose_description:['用舒服的姿勢坐下來','把手掌合起來，一邊吸氣打開心胸','想像慢慢交叉的手臂靠攏的感覺','讓一大口的新鮮的空氣送到自己身體裡','一邊吐氣一邊放鬆','重複5-10次'],
                pose_ai:false,
            },
            {
                pose_id: 'third',
                pose_brief: '打開自己，全世界都會幫助妳！',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L13_action03.mp4',
                pose_description:['先用舒適的姿勢坐下來','從鼻子慢慢地吸氣','把兩手抬上去，讓背部伸直','一邊吐氣邊讓兩手慢慢放下','在腰的後面交叉手指，吸氣用肩膀擴胸','感受背部的肌肉，讓肩胛骨靠近','維持三到五個呼吸','吐氣的時候把兩手慢慢放回去，調整呼吸'],
                pose_ai:true,
            },
        ],
    },
    {
        id: '14',
        title: '調整自律神經的瑜珈',
        chapter_flag: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/unit14.svg',
        tags: ['blend'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/course-preview-14.png',
        video_url:'https://player.vimeo.com/video/349829709',
        video_url_jp:'https://player.vimeo.com/video/349838572',
        course_introduction:'因為產後生活都是以嬰兒為中心。想要休息的時候也沒有辦法休息，不知不覺就會累積很多疲勞對吧？微量的疲勞如果一直放著不管，就會累積起來，搞壞身體。<br>所以，媽媽們要記得為自己確保一些照顧身體的時間，才有活力可以迎接每一天哦！',
        poses:[
            {
                pose_id: 'first',
                pose_brief: '讓體內循環變好，全身都可以獲得氧氣',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L14_action01.mp4',
                pose_description:['先把右手放到肚子上','左手放在胸部附近','慢慢地從鼻子吸氣','把空氣送到胸部，再送到肚子','慢慢地從嘴巴吐一口薄薄的氣','重複30秒到1分鐘'],
                pose_ai:false,
            },
            {
                pose_id: 'second',
                pose_brief: '平衡自律神經',
                pose_video:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/mamiyoga-course/L14_action02.mp4',
                pose_description:['採取四肢趴在地上的姿勢','四肢趴在地上的姿勢是用到全身的核心肌肉的姿勢','肩膀底下對應到手腕的位置，膝蓋來到腰下的位置','整個背部呈現平穩直線','先吐氣、一邊吸氣，讓屁股抬起來，把背部凹進去','臉往斜上方、一邊吐氣一邊讓背變圓','把臉朝下、這樣重複三到五次'],
                pose_ai:false,
            },
        ],
    },

]
    