module.exports = [
    {
        id: '1',
        title: '用空气启动身体',
        tags: ['primary'],
        record_time:'20-45',
        ai_teacher: true,
        is_front: true,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-1.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-1.mp4',
        pose_description:['轻松盘腿坐在垫子上','吸气，把右手向上抬起','吐气，身体往左倾、意识到右侧身体的肌肉伸展','吸气，换左手向上抬起','吐气，身体往右倾、意识到左侧身体的肌肉伸展','重复三到五次'],
        upload_id: '8',
        upload_notices:['姿势正确','身体往后倒','手摆到身体后方','手摆到身体前方','身体重心押在左手上','身体重心押在右手上']
    },
    {
        id: '2',
        title: '改善背部与肩部僵硬',
        tags: ['primary'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-2.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-2.mp4',
        pose_description:['采取轻松的姿势坐下','在胸前把手臂交叉','一边吐气让背部稍微拱起','将双手十指交扣','想像腹部跟手腕当中产生空间','吸气让身体舒展开','将双手放到身体后方十指交扣','意识到两边的肩胛骨向脊椎靠近','把气全部吐完后，下一次呼吸时扩胸','更进一步的人，可以把脸朝上试试看','回到原本位置时要慢慢地回去，再把手放开'],
    },
    {
        id: '3',
        title: '用呼吸创造放松空间',
        tags: ['primary'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-3.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-3.mp4',
        pose_description:['设置瑜珈砖和瑜珈枕后，把屁股后面垫上瑜珈砖','没有瑜珈砖和瑜珈枕的人可以用棉被裹起来代替','将背部靠在上面，慢慢地面朝天空地躺下来，让脚底碰到地板','把手放在肚子上，像是要温暖他ㄧ般，或是把手掌面向上，放到身体两侧','慢慢地放轻松，把身体的力量抽掉','放松持续三到五个呼吸','回去的时候把脚闭合，把手放下','让手肘压着垫子，起身']
    },
    {
        id: '4',
        title: '让全身的神经进入休息',
        tags: ['primary'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-4.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-4.mp4',
        pose_description:['先仰躺看天花板，让脚开与垫子同宽','手掌面向天花板，在腋下留一个拳头的空间','慢慢地闭上眼睛把全身的力量都交给垫子','把头左右摇一摇、滚一滚','从口中吐哈～这样的把全身力量放松','进行5-10分钟，不让身体变冷的程度','持续着自然的呼吸','起身的时候，先从末端的手足收紧、放松（石头、布、石头、布），开着握着重复','让整个身体起床','再把头左右摇晃，让两个膝盖立起来','把身体往旁边，慢慢地起身'],
    },
    {
        id: '5',
        title: '全世界都会帮助你！',
        tags: ['primary'],
        record_time:'20-45',
        ai_teacher: true,
        is_front:false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-5.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-5.mp4',
        pose_description:['先用舒适的姿势坐下来','从鼻子慢慢地吸气','把两手抬上去，让背部伸直','一边吐气边让两手慢慢放下','在腰的后面交叉手指，吸气用肩膀扩胸','感受背部的肌肉，让肩胛骨靠近','维持三到五个呼吸','吐气的时候把两手慢慢放回去，调整呼吸'],
        upload_id: '27',
        upload_notices:['姿势正确','耸肩','身体往后倒','身体往前倒','背部弯曲','手伸不够直','抬手不完全','伸展不完全','未坐下']
    },
    {
        id: '6',
        title: '回到没有歪斜的骨盆',
        tags: ['intermediate'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-6.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-6.mp4',
        pose_description:['首先模仿趴睡的姿势','两只手肘将上半身撑起','调整手肘让双臂与肩同宽','抱持手肘位置，右膝盖往腰部下方靠近','右膝撑地，用大腿的力量将身体撑起','右腿：腰部与大腿是九十度、大腿与小腿也是九十度','左腿：大腿小腿贴在地板上，脚掌朝后与小腿90度','脸部朝前，重复三到五次呼吸','另一边也做相同的动作','屁股碰到后脚跟，手伸直手掌贴地伸直背部后缓缓坐起']
    },
    {
        id: '7',
        title: '减缓腰部疼痛',
        tags: ['intermediate'],
        record_time:'20-45',
        ai_teacher: true,
        is_front:true,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-7.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-7.mp4',
        pose_description:['正躺，眼睛看向天花板','左膝抬高，两手抱住膝盖','双掌托住膝盖，让双手臂伸直','将右脚抬起，用腰部的力量将整条腿做上下摆动三到五次','腰部有一点拱起来是可以的','如果很吃力的同学可以把毛巾捲起来放在腰下','右脚做完，换左边做三到五次'],
        upload_id: '6',
        upload_notices:['姿势正确','膝盖弯曲','膝盖弯曲','抬腿速度太快','抬腿速度太快','轴心不稳']
    },
    {
        id: '8',
        title: '打通压力沉积的地方',
        tags: ['intermediate'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-8.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-8.mp4',
        pose_description:['坐在垫子上，将脚掌对脚掌','两手各握住两边脚趾','将左脚伸直','右脚弯曲且靠拢耻骨','让伸展的左脚跟往后扣、脚趾朝自己方向','一边吸气、一边扩胸','一边吐气、一边前倾','一边吸入空气、放松','最后慢慢将上半身撑起来','换边，以反方向换腿做一样的动作']
    },
    {
        id: '9',
        title: '锻鍊产后腹肌',
        tags: ['intermediate'],
        record_time:'20-45',
        ai_teacher: true,
        is_front:false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-9.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-9.mp4',
        pose_description:['仰躺看着天花板，将脚掌贴地，把两个膝盖立起','把两手伸直往前伸','一边吸气然后一边吐气，专注着下腹的部分','轻轻地将上半身往前抬','收起下巴，吸气，吐气，慢慢上来','重复10次'],
        upload_id: '19',
        upload_notices:['姿势正确','脚步太开让力量不足','没有用核心的肌肉力量，只靠一鼓作气']
    },
    {
        id: '10',
        title: '平衡自律神经',
        tags: ['intermediate'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-10.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-10.mp4',
        pose_description:['采取四肢趴在地上的姿势','四肢趴在地上的姿势是用到全身的核心肌肉的姿势','肩膀底下对应到手腕的位置，膝盖来到腰下的位置','整个背部呈现平稳直线','先吐气、一边吸气，让屁股抬起来，把背部凹进去','脸往斜上方、一边吐气一边让背变圆','把脸朝下、这样重复三到五次']
    },
    {
        id: '11',
        title: '让肚子变得更紧实',
        tags: ['advanced'],
        record_time:'20-45',
        ai_teacher: true,
        is_front:false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-11.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-11.mp4',
        pose_description:['曲膝坐下','两手放在膝盖后方','直直的挺立背部，以腹肌的力量把脚抬起来','维持将脚弯曲成90度的动作','放在膝盖的手，边开扩胸边慢慢地往前伸','维持三到五次的呼吸','把手放回膝盖后方的位置','一边吐气把脚放在地上调整呼吸'],
        upload_id: '15',
        upload_notices:['姿势正确','脚抬得太低','脚抬得太高','手臂抬太低','手臂抬太高','背部弯曲']
    },
    {
        id: '12',
        title: '回复产后的翘臀',
        tags: ['advanced'],
        ai_teacher: false,
        preview_img: 'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-preview-12.jpg',
        video_url:'https://ludo-beta.s3-ap-southeast-1.amazonaws.com/static/mommiyoga/course/course-video-12.mp4',
        pose_description:['将四肢都趴在地上，调整呼吸','膝盖呈90度，然后让大腿跟地垫呈现平行的状态','把腿往后抬起来','骨盆一旦变成跟垫子平行，就要注意腰部不要太开','要一边注意一边这些细节，一边进行动作','一边吸气，一边把膝盖放到右边','保持与腰同高，接着，放下来','我们就这样连续重复三次','换边','结束之后，就要把屁股放回后脚跟，把头放下稍微休息']
    },
]
    